'use client';
import Link from 'next/link';
import { useAtmos } from '@/providers/atmos-provider';
import { boards } from '@/mock/catalog';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';

export default function Profile(){const a=useAtmos();return <div className="profile-layout"><div className="profile-top"><div className="profile-avatar">f</div><div><h1>Your little world.</h1><p>Guest explorer · {a.sessions.length} saved moods</p></div></div><div className="demo-notice">You’re exploring the demo collection. Saves stay in this browser. Original Far.Fly audio lets you try the complete music experience.</div><section className="settings-section"><h2>Make yourself at home</h2><p>Sign in to your connected Supabase account when this app is configured.</p><div className="setting-row"><span>Keep your atmosphere close.</span><Link href="/auth" className="secondary">Sign in</Link></div></section><section className="settings-section"><h2>Your visual worlds</h2><p>Only selected boards shape your recommendations.</p><div className="board-grid">{boards.map(b=><label key={b}><Checkbox aria-label={b} checked={a.enabledBoards.includes(b)} onCheckedChange={checked=>a.setEnabledBoards(checked?[...a.enabledBoards,b]:a.enabledBoards.filter(x=>x!==b))}/>{b}</label>)}</div><div className="setting-row"><div><strong>Pinterest</strong><p>{a.pinterest.connected?'Connected · choose your visual worlds':'Not connected · demo collection available'}</p></div><Link className="secondary" href="/pinterest">{a.pinterest.connected?'Manage connection':'Connection details'}</Link></div></section><section className="settings-section"><h2>Your colours</h2><p>Let pictures colour your whole world, follow the soundtrack mood, or keep the original theme.</p><div className="setting-row"><label htmlFor="theme-choice">Appearance</label><select id="theme-choice" className="secondary" value={a.themeMode} onChange={e=>a.setThemeMode(e.target.value as 'visuals'|'mood'|'fixed')}><option value="visuals">Follow visuals</option><option value="mood">Follow mood</option><option value="fixed">Fixed theme</option></select></div></section><section className="settings-section"><h2>Your soundtrack, your choice</h2><div className="setting-row"><div><strong>Adaptive recommendations</strong><p>Let selected visual activity shape the songs coming next.</p></div><Switch aria-label="Adaptive recommendations" checked={a.adaptive} onCheckedChange={a.setAdaptive}/></div><div className="setting-row"><div><strong>Start with a fresh atmosphere</strong><p>Clear recent signals and music history. Your saves stay safe.</p></div><button className="secondary" onClick={a.clearHistory}>Clear history</button></div></section><section className="settings-section"><h2>About your atmosphere</h2><p>Far.Fly uses visual themes to suggest music, without making claims about your emotional or psychological state. Demo image analysis is local and deterministic. No images or browsing activity are sent to AI services in demo mode.</p></section></div>;}

