import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const modules=new Map();
async function moduleUrl(path){
 if(modules.has(path))return modules.get(path);
 let source=ts.transpileModule(fs.readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
 const dependencies=[...source.matchAll(/from ['"](\.[^'"]+)['"]/g)];
 for(const match of dependencies){
  const resolved=new URL(match[1]+'.ts',new URL(path,import.meta.url));
  const child=await moduleUrl(resolved.href);
  source=source.replace(match[0],'from '+JSON.stringify(child));
 }
 const url='data:text/javascript;base64,'+Buffer.from(source).toString('base64');
 modules.set(path,url);return url;
}
const {handleSpotify}=await import(await moduleUrl('../lib/spotify-server.ts'));
const {seal,unseal}=await import(await moduleUrl('../lib/spotify-session.ts'));
const origin='https://farfly.vercel.app', key='a'.repeat(64);
process.env.SPOTIFY_SESSION_KEY=key;
const call=(path,opts={})=>handleSpotify(new Request(origin+'/api/spotify/'+path,opts));
assert.equal((await call('token')).status,405);
assert.equal((await call('token',{method:'POST',headers:{origin:'https://evil.example'}})).status,403);
const start=await call('connect',{method:'POST',headers:{origin}});
const target=new URL(start.headers.get('location'));
assert.equal(target.searchParams.get('code_challenge_method'),'S256');
assert.equal(target.searchParams.get('redirect_uri'),origin+'/api/spotify/callback');
const stateCookie=start.headers.getSetCookie()[0].split(';')[0];
assert.match(start.headers.getSetCookie()[0],/HttpOnly; Secure; SameSite=Lax/);
const state=JSON.parse((await unseal(stateCookie.slice('sp_state='.length),'state',key)).value);
assert.equal(target.searchParams.get('code_challenge'),Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(state.verifier))).toString('base64url'));
let calls=0;
globalThis.fetch=async(url,opts)=>{calls++;assert.equal(opts.body.get('code_verifier'),state.verifier);return Response.json({access_token:'access',refresh_token:'refresh',expires_in:3600,scope:'streaming user-read-email user-read-private user-modify-playback-state'});};
assert.match((await call('callback?code=x&state=wrong',{headers:{cookie:stateCookie}})).headers.get('location'),/invalid_state/);
assert.equal(calls,0);
const callback=await call('callback?code=x&state='+state.state,{headers:{cookie:stateCookie}});
assert.match(callback.headers.get('location'),/connected/);
const cookies=callback.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
assert.equal((await (await call('token',{method:'POST',headers:{origin,cookie:cookies}})).json()).access_token,'access');
assert.match(callback.headers.get('cache-control'),/no-store/);
assert.equal((await call('play',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({device:'x',uri:'https://evil.example'})})).status,400);
const refreshCookie='sp_refresh='+await seal('refresh','refresh',Date.now()+600000,key);
globalThis.fetch=async()=>Response.json({error:'temporarily_unavailable'},{status:503});
const transient=await call('token',{method:'POST',headers:{origin,cookie:refreshCookie}});
assert.equal(transient.status,503);assert.equal(transient.headers.getSetCookie().length,0);
globalThis.fetch=async()=>Response.json({access_token:'renewed',refresh_token:'rotated',expires_in:3600});
const renewed=await call('token',{method:'POST',headers:{origin,cookie:refreshCookie}});
assert.equal((await renewed.json()).access_token,'renewed');assert.equal(renewed.headers.getSetCookie().length,2);
globalThis.fetch=async()=>Response.json({error:'invalid_grant'},{status:400});
const revoked=await call('token',{method:'POST',headers:{origin,cookie:refreshCookie}});
assert.equal(revoked.status,401);assert.equal(revoked.headers.getSetCookie().length,3);
const logout=await call('connection',{method:'POST',headers:{origin,cookie:cookies}});
assert.equal(logout.headers.getSetCookie().length,3);
const {seal:pinSeal}=await import(await moduleUrl('../lib/pinterest-session.ts'));
assert.equal(await unseal(await pinSeal('access','x',Date.now()+60000,key),'access',key),null);
console.log('PASS: Spotify PKCE, state validation, scope validation, origin guard, token cookies, refresh rotation, transient failures, revocation, logout and provider separation.');

const {pictureMood,dominantMood}=await import(await moduleUrl('../lib/picture-mood.ts'));
const {recommendationQueue,nextRecommendation,trackFinished,normalizeSpotify}=await import(await moduleUrl('../lib/spotify-discovery.ts'));
const base={title:'',tags:[],mood:{dreamy:.2,nostalgic:.2,calm:.2,warm:.2,energetic:.2,cinematic:.2}};
assert.equal(dominantMood(pictureMood({...base,title:'sunset beach summer'},{hue:25,saturation:40,dark:false})),'warm');
assert.equal(dominantMood(pictureMood({...base,title:'quiet forest rain'},{hue:170,saturation:20,dark:false})),'calm');
const old={id:'old'},fresh=[{id:'a'},{id:'b'}];
assert.deepEqual(recommendationQueue(old,fresh),[old,...fresh]);assert.deepEqual(fresh,[{id:'a'},{id:'b'}]);
assert.equal(nextRecommendation('old',fresh).id,'a');assert.equal(nextRecommendation('a',fresh).id,'b');
assert.equal(trackFinished({id:'a',paused:false,position:99000,duration:100000},{id:'a',paused:true,position:0,duration:100000}),true);
assert.equal(trackFinished({id:'a',paused:false,position:50000,duration:100000},{id:'a',paused:true,position:50000,duration:100000}),false);
const makeTrack=(id,name='Song',artist='Artist')=>({id,name,artists:[{name:artist}],duration_ms:100000,is_playable:true,album:{images:[]}});
const item=makeTrack('a'.repeat(22));
assert.equal(normalizeSpotify([item,item,{...item,id:'b'.repeat(22)},{...item,id:'c'.repeat(22),is_playable:false}]).length,1);
calls=0;globalThis.fetch=async(url,opts)=>{calls++;assert.match(url,/api.spotify.com\/v1\/search/);assert.equal(new Headers(opts.headers).get('Authorization'),'Bearer access');return Response.json({tracks:{items:[item,makeTrack('b'.repeat(22),'Other','Another')]}});};
const rec=await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'calm'})});
assert.equal(rec.status,200);assert.equal((await rec.json()).tracks.length,2);assert.equal(calls,2);
assert.equal((await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'__proto__'})})).status,400);
assert.equal(calls,2);
globalThis.fetch=async()=>Response.json({}, {status:429});
assert.equal((await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'calm'})})).status,429);
console.log('PASS: picture mood, current-track preservation, fresh queue order, natural end versus pause, deduplication, authenticated Spotify search and rate limits.');

const jsonConnect=await call('connect',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:'{}'});
assert.equal(jsonConnect.status,200);assert.equal(new URL((await jsonConnect.json()).url).origin,'https://accounts.spotify.com');assert.ok(jsonConnect.headers.getSetCookie().some(c=>c.startsWith('sp_state=')));

const {discoveryPage}=await import(await moduleUrl('../lib/spotify-discovery.ts'));
assert.notDeepEqual(discoveryPage('warm',0).queries,discoveryPage('warm',1).queries);
assert.equal(discoveryPage('warm',3).offset,10);
assert.equal(dominantMood(pictureMood({...base,title:'Coffee table with books',mood:{...base.mood,cinematic:1}},{hue:0,saturation:0,dark:true})),'warm');
assert.equal(dominantMood(pictureMood({...base,title:'Cosy cafe latte'},{hue:240,saturation:20,dark:true})),'warm');
const searchUrls=[];
globalThis.fetch=async url=>{searchUrls.push(new URL(url));return Response.json({tracks:{items:[]}});};
const later=await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'warm',page:3})});
assert.equal(later.status,200);assert.equal((await later.json()).hasMore,true);
assert.ok(searchUrls.every(u=>u.searchParams.get('offset')==='10'));
assert.equal((await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'warm',page:30})})).status,400);
console.log('PASS: coffee scenes outweigh old tags, broader styles, paginated search and bounded discovery.');

const {pictureVariation,recommendationsForPicture}=await import(await moduleUrl('../lib/spotify-discovery.ts'));
const firstPin=pictureVariation('pinterest-1126251819319171606'),secondPin=pictureVariation('pinterest-1126251819293128864');
assert.notDeepEqual(discoveryPage('calm',0,firstPin),discoveryPage('calm',0,secondPin));
assert.deepEqual(recommendationsForPicture('old','new',false,fresh),[]);
assert.deepEqual(recommendationsForPicture('new','new',true,fresh),[]);
assert.deepEqual(recommendationQueue(old,recommendationsForPicture('old','new',false,fresh)),[old]);
assert.deepEqual(recommendationsForPicture('new','new',false,fresh),fresh);
assert.equal((await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'calm',variation:30})})).status,400);
searchUrls.length=0;
await call('recommendations',{method:'POST',headers:{origin,cookie:cookies},body:JSON.stringify({mood:'calm',variation:3})});
assert.ok(searchUrls.every(u=>u.searchParams.get('offset')==='10'));
console.log('PASS: different Pinterest pictures vary search, stale cards are hidden, current song retained, variation validated.');

